name: CI
on:
  push:
    branches:
      - master
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bazel-version:
          - 3.5.1
          - 3.6.0
          - 3.7.1
          - 3.7.2
          - 4.0.0
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup bazel
        run: |
          TOOLS_DIR="${HOME}/.cache/tools"
          mkdir -p "${TOOLS_DIR}/bin"
          curl -Ls -o "${TOOLS_DIR}/bin/bazel" "https://github.com/bazelbuild/bazelisk/releases/download/v1.7.5/bazelisk-linux-amd64"
          chmod +x "${TOOLS_DIR}/bin/bazel"
          echo "${TOOLS_DIR}/bin" >> $GITHUB_PATH
      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/bazel
          key: bazel-${{ matrix.bazel-version }}-${{ github.sha }}
          restore-keys: |
            bazel-${{ matrix.bazel-version }}-
            bazel-
      - name: Run bazel @nodejs//:yarn
        run: bazel run @nodejs//:yarn
      - name: Run bazel check
        run: yarn run bazel:format-check && yarn run bazel:lint
      - name: Run bazel build
        run: bazel build //... --announce_rc --noshow_progress --verbose_failures --local_ram_resources=7000
      - name: Run bazel test
        run: bazel test //... --announce_rc --noshow_progress --verbose_failures --local_ram_resources=7000 --test_output=all